### ISSUE TITLE
ViewHolder pattern

### ISSUE THREAD

**Issue by BrendonSled** [filbabic/FlexibleAdapter#1]
Wouldn't this totally negate the ViewHolder pattern?

**Comment by filbabic** [comment]
In some way yes it might, though from my testing, I haven't experienced much overhead(if any), from the views not being recycled. Though having them recycled is quite simple, and I'll add it in a new bugfix build. Thanks for pointing it out! :)

**Comment by BrendonSled** [comment]
Awesome, I'll be looking forward to seeing your implementation
